### ISSUE TITLE
What is the .aar file for and how to build it yourself?

### ISSUE THREAD

**Issue by yb-cs** [wkt/YoloMobile#1]
Hello,

Can you please explain to me what is the .aar file for. And how can we modify it or build one ourselves?

Thank you,
Regards,
YB.

**Comment by yb-cs** [comment]
I want to work on this library and add support maybe to different dimensions, etc. So if you would help me with this inquiry it would be great.

**Comment by wkt** [comment]
About .aar you may goto https://developer.android.com/studio/projects/android-library
And I have change the README.md, tell how to build a .aar by yourself.
You are free to build a new .aar file after modify the code.
