### ISSUE TITLE
不使用配置文件 可以吗？

### ISSUE THREAD

**Issue by jing1007209484** [wkt/YoloMobile#11]
package com.yolo.yolo.impl;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.util.Log;

import com.weiketing.yolomobile.YoloInfer;
import com.yolo.yolo.MyLog;

import java.util.List;

public class YoloOperator {

        private YoloInfer yoloInfer;
    private String TAG=YoloOperator.class.getName();

    public YoloOperator() {
    }

    /**
     * 初始化 YoloInfer 实例并设置模型路径
     * @param context 应用上下文
     * @param paramPath 模型的 param 文件路径
     * @param binPath 模型的 bin 文件路径
     */
    public void initialize(Context context, String paramPath, String binPath)
    {
        try {
            yoloInfer = new YoloInfer(context);
            yoloInfer.setParamName(paramPath);
            yoloInfer.setBinName(binPath);
            yoloInfer.loadModel();
        } catch (Exception e) {
            MyLog.d(TAG, "initialize: ",e.getMessage());
        }

    }

    /**
     * 对给定的图像进行目标检测
     * @param bitmap 输入的图像
     * @return 检测结果，包含检测到的对象的边界框和类别
     */
    public List<YoloInfer.Box> detectObjects(Bitmap bitmap) {

//        List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);
        List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);

        return boxList;
    }

    /**
     * 在画布上绘制检测结果
     * @param canvas 要绘制的画布
     * @param boxes 检测结果列表
     * @param paint 绘制时使用的画笔
     */
    public void drawResults(Canvas canvas, List<YoloInfer.Box> boxes, Paint paint) {
        YoloInfer.draw(canvas, boxes, paint);
    }

}
这样的  写法 可以吗？？

**Comment by wkt** [comment]
> package com.yolo.yolo.impl;
> 
> import android.content.Context; import android.graphics.Bitmap; import android.graphics.Canvas; import android.graphics.Paint; import android.util.Log;
> 
> import com.weiketing.yolomobile.YoloInfer; import com.yolo.yolo.MyLog;
> 
> import java.util.List;
> 
> public class YoloOperator {
> 
> ```
>     private YoloInfer yoloInfer;
> private String TAG=YoloOperator.class.getName();
> 
> 
> public YoloOperator() {
> }
> 
> /**
>  * 初始化 YoloInfer 实例并设置模型路径
>  * @param context 应用上下文
>  * @param paramPath 模型的 param 文件路径
>  * @param binPath 模型的 bin 文件路径
>  */
> public void initialize(Context context, String paramPath, String binPath)
> {
>     try {
>         yoloInfer = new YoloInfer(context);
>         yoloInfer.setParamName(paramPath);
>         yoloInfer.setBinName(binPath);
>         yoloInfer.loadModel();
>     } catch (Exception e) {
>         MyLog.d(TAG, "initialize: ",e.getMessage());
>     }
> 
> }
> 
> /**
>  * 对给定的图像进行目标检测
>  * @param bitmap 输入的图像
>  * @return 检测结果，包含检测到的对象的边界框和类别
>  */
> public List<YoloInfer.Box> detectObjects(Bitmap bitmap) {
> ```
> 
> // List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap); List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);
> 
> ```
>     return boxList;
> }
> 
> /**
>  * 在画布上绘制检测结果
>  * @param canvas 要绘制的画布
>  * @param boxes 检测结果列表
>  * @param paint 绘制时使用的画笔
>  */
> public void drawResults(Canvas canvas, List<YoloInfer.Box> boxes, Paint paint) {
>     YoloInfer.draw(canvas, boxes, paint);
> }
> ```
> 
> } 这样的 写法 可以吗？？

原则上不用配置文件也是可以的，做法类似：
        yoloInfer = new YoloInfer(context);
        yoloInfer.setParamName(paramPath);
        yoloInfer.setBinName(binPath);
        yoloInfer.setInputName(inputName);
        yoloInfer.setInputSize(inputSize);
        yoloInfer.loadModel();
       yoloInfer.addOutput(outputName,stride,anchors);
      ...
 更具体的可参考：
> https://github.com/wkt/YoloMobile/blob/main/YoloMobile/src/main/java/com/weiketing/yolomobile/YoloInfer.java
public void loadFromJson(String json,String jsonDir)

**Comment by jing1007209484** [comment]
package com.yolo.yolo.impl;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.util.Log;

import com.weiketing.yolomobile.YoloInfer;
import com.yolo.yolo.MyLog;


import java.util.List;

public class YoloOperator {

        private YoloInfer yoloInfer;
    private String TAG=YoloOperator.class.getName();
    private static YoloOperator instance = null;

    public YoloOperator() {
    }


    public static YoloOperator getInstance() {
        if (instance == null) {
            synchronized (YoloOperator.class) {
                if (instance == null) {
                    instance = new YoloOperator();
                }
            }
        }
        return instance;
    }


    /**
     * 初始化 YoloInfer 实例并设置模型路径
     * @param context 应用上下文
     * @param paramPath 模型的 param 文件路径
     * @param binPath 模型的 bin 文件路径
     */
    public void initialize(Context context, String paramPath, String binPath)
    {
        try {
//            yoloInfer = new YoloInfer(context);
//            yoloInfer.setParamName(paramPath);
//            yoloInfer.setBinName(binPath);
//            yoloInfer.loadModel();
//


            yoloInfer = new YoloInfer(context);
            yoloInfer.setParamName(paramPath);
            yoloInfer.setBinName(binPath);
         yoloInfer.setBoxThreshold(0.5F);
         yoloInfer.setIouThreshold(0.5F);


            yoloInfer.setInputSize(640);
            yoloInfer.loadModel();

            yoloInfer.setInputName("images");
//            yoloInfer.addOutput(outputName,stride,anchors);
            yoloInfer.bindCPU(YoloInfer.BIND_CPU_BIG);


        } catch (Exception e) {
            MyLog.d(TAG, "initialize: ",e.getMessage());
        }

    }

    /**
     * 对给定的图像进行目标检测
     * @param bitmap 输入的图像
     * @return 检测结果，包含检测到的对象的边界框和类别
     */
    public List<YoloInfer.Box&gt; detectObjects(Bitmap bitmap) {

//        List<YoloInfer.Box&gt; boxList=yoloInfer.detect(bitmap);
        List<YoloInfer.Box&gt; boxList=yoloInfer.detect(bitmap);
        MyLog.d(TAG, "识别出: ",boxList.size());

        return boxList;
    }

    /**
     * 在画布上绘制检测结果
     * @param canvas 要绘制的画布
     * @param boxes 检测结果列表
     * @param paint 绘制时使用的画笔
     */
    public void drawResults(Canvas canvas, List<YoloInfer.Box&gt; boxes, Paint paint) {
        YoloInfer.draw(canvas, boxes, paint);
    }

}


无法 识别出来 是0个&nbsp; &nbsp;不知道哪里出现问题


梦幻雪月
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wkt/YoloMobile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 中午12:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wkt/YoloMobile] 不使用配置文件 可以吗？ (Issue #11)



  package com.yolo.yolo.impl;
 import android.content.Context; import android.graphics.Bitmap; import android.graphics.Canvas; import android.graphics.Paint; import android.util.Log;
 import com.weiketing.yolomobile.YoloInfer; import com.yolo.yolo.MyLog;
 import java.util.List;
 public class YoloOperator {
 private YoloInfer yoloInfer; private String TAG=YoloOperator.class.getName(); public YoloOperator() { }/*** 初始化 YoloInfer 实例并设置模型路径* @param context 应用上下文* @param paramPath 模型的 param 文件路径* @param binPath 模型的 bin 文件路径*/ public void initialize(Context context, String paramPath, String binPath) { try { yoloInfer = new YoloInfer(context); yoloInfer.setParamName(paramPath); yoloInfer.setBinName(binPath); yoloInfer.loadModel(); } catch (Exception e) { MyLog.d(TAG, "initialize: ",e.getMessage()); }}/*** 对给定的图像进行目标检测* @param bitmap 输入的图像* @return 检测结果，包含检测到的对象的边界框和类别*/ public List<YoloInfer.Box&gt; detectObjects(Bitmap bitmap) { 
 // List<YoloInfer.Box&gt; boxList=yoloInfer.detect(bitmap); List<YoloInfer.Box&gt; boxList=yoloInfer.detect(bitmap);
 return boxList; }/*** 在画布上绘制检测结果* @param canvas 要绘制的画布* @param boxes 检测结果列表* @param paint 绘制时使用的画笔*/ public void drawResults(Canvas canvas, List<YoloInfer.Box&gt; boxes, Paint paint) { YoloInfer.draw(canvas, boxes, paint); } 
 } 这样的 写法 可以吗？？
  原则上不用配置文件也是可以的，做法类似：
 yoloInfer = new YoloInfer(context);
 yoloInfer.setParamName(paramPath);
 yoloInfer.setBinName(binPath);
 yoloInfer.setInputName(inputName);
 yoloInfer.setInputSize(inputSize);
 yoloInfer.loadModel();
 yoloInfer.addOutput(outputName,stride,anchors);
 ...
 更具体的可参考：
  https://github.com/wkt/YoloMobile/blob/main/YoloMobile/src/main/java/com/weiketing/yolomobile/YoloInfer.java
 public void loadFromJson(String json,String jsonDir)

**Comment by wkt** [comment]
> yoloInfer.setParamName(paramPath);
> yoloInfer.setBinName(binPath);
> yoloInfer.setInputName(inputName);
> yoloInfer.setInputSize(inputSize);

```
yoloInfer.setParamName(paramPath);
yoloInfer.setBinName(binPath);
yoloInfer.setInputName(inputName);
yoloInfer.setInputSize(inputSize);
```
必须在yoloInfer.loadModel()之前

**Comment by jing1007209484** [comment]
package com.yolo.yolo.impl;

import android.content.Context;
import android.graphics.Bitmap;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.util.Log;

import com.weiketing.yolomobile.YoloInfer;
import com.yolo.yolo.MyLog;
import com.yolo.yolo.entity.Recognition;


import java.util.ArrayList;
import java.util.List;

public class YoloOperator {

        private YoloInfer yoloInfer;
    private String TAG=YoloOperator.class.getName();
    private static YoloOperator instance = null;

    public YoloOperator() {
    }


    public static YoloOperator getInstance() {
        if (instance == null) {
            synchronized (YoloOperator.class) {
                if (instance == null) {
                    instance = new YoloOperator();
                }
            }
        }
        return instance;
    }


    /**
     * 初始化 YoloInfer 实例并设置模型路径
     * @param context 应用上下文
     * @param paramPath 模型的 param 文件路径
     * @param binPath 模型的 bin 文件路径
     */
    public void initialize(Context context, String paramPath, String binPath) {
        try {
            yoloInfer = new YoloInfer(context);  // 创建 YoloInfer 实例
            yoloInfer.setParamName(paramPath);   // 设置模型的 param 文件路径
            yoloInfer.setBinName(binPath);       // 设置模型的 bin 文件路径

            yoloInfer.setBoxThreshold(0.2F);     // 设置 BoxThreshold
            yoloInfer.setIouThreshold(0.2F);     // 设置 IouThreshold
            yoloInfer.setInputSize(640);         // 设置输入尺寸
            yoloInfer.setInputName("input");


            // yoloInfer.addOutput(outputName,stride,anchors); // 注释掉的输出配置
            yoloInfer.bindCPU(YoloInfer.BIND_CPU_BIG);  // 绑定 CPU

            yoloInfer.loadModel();  // 加载模型

        } catch (Exception e) {
            MyLog.d(TAG, "initialize: ", e.getMessage());
        }
    }


    /**
     * 对给定的图像进行目标检测
     * @param bitmap 输入的图像
     * @return 检测结果，包含检测到的对象的边界框和类别
     */
    public List<Recognition> detectObjects(Bitmap bitmap) {

//        List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);
        List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);

        List<Recognition>list=new ArrayList<>();
        for (YoloInfer.Box box : boxList) {
            Recognition ionic=new Recognition(String.valueOf(box.c),box.p,box.rect.left,box.rect.top,box.rect.width(),box.rect.height());

            list.add(ionic);


        }

        MyLog.d(TAG, "识别出: ",boxList.size());

        return list;
    }

    /**
     * 在画布上绘制检测结果
     * @param canvas 要绘制的画布
     * @param boxes 检测结果列表
     * @param paint 绘制时使用的画笔
     */
    public void drawResults(Canvas canvas, List<YoloInfer.Box> boxes, Paint paint) {
        YoloInfer.draw(canvas, boxes, paint);
    }

}
不行呀     识别出 0个 也不知道哪里出错了 也没有任何提示  这些写对还是不对？

**Comment by wkt** [comment]
> package com.yolo.yolo.impl;
> 
> import android.content.Context; import android.graphics.Bitmap; import android.graphics.Canvas; import android.graphics.Paint; import android.util.Log;
> 
> import com.weiketing.yolomobile.YoloInfer; import com.yolo.yolo.MyLog; import com.yolo.yolo.entity.Recognition;
> 
> import java.util.ArrayList; import java.util.List;
> 
> public class YoloOperator {
> 
> ```
>     private YoloInfer yoloInfer;
> private String TAG=YoloOperator.class.getName();
> private static YoloOperator instance = null;
> 
> public YoloOperator() {
> }
> 
> 
> public static YoloOperator getInstance() {
>     if (instance == null) {
>         synchronized (YoloOperator.class) {
>             if (instance == null) {
>                 instance = new YoloOperator();
>             }
>         }
>     }
>     return instance;
> }
> 
> 
> /**
>  * 初始化 YoloInfer 实例并设置模型路径
>  * @param context 应用上下文
>  * @param paramPath 模型的 param 文件路径
>  * @param binPath 模型的 bin 文件路径
>  */
> public void initialize(Context context, String paramPath, String binPath) {
>     try {
>         yoloInfer = new YoloInfer(context);  // 创建 YoloInfer 实例
>         yoloInfer.setParamName(paramPath);   // 设置模型的 param 文件路径
>         yoloInfer.setBinName(binPath);       // 设置模型的 bin 文件路径
> 
>         yoloInfer.setBoxThreshold(0.2F);     // 设置 BoxThreshold
>         yoloInfer.setIouThreshold(0.2F);     // 设置 IouThreshold
>         yoloInfer.setInputSize(640);         // 设置输入尺寸
>         yoloInfer.setInputName("input");
> 
> 
>         // yoloInfer.addOutput(outputName,stride,anchors); // 注释掉的输出配置
>         yoloInfer.bindCPU(YoloInfer.BIND_CPU_BIG);  // 绑定 CPU
> 
>         yoloInfer.loadModel();  // 加载模型
> 
>     } catch (Exception e) {
>         MyLog.d(TAG, "initialize: ", e.getMessage());
>     }
> }
> 
> 
> /**
>  * 对给定的图像进行目标检测
>  * @param bitmap 输入的图像
>  * @return 检测结果，包含检测到的对象的边界框和类别
>  */
> public List<Recognition> detectObjects(Bitmap bitmap) {
> ```
> 
> // List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap); List<YoloInfer.Box> boxList=yoloInfer.detect(bitmap);
> 
> ```
>     List<Recognition>list=new ArrayList<>();
>     for (YoloInfer.Box box : boxList) {
>         Recognition ionic=new Recognition(String.valueOf(box.c),box.p,box.rect.left,box.rect.top,box.rect.width(),box.rect.height());
> 
>         list.add(ionic);
> 
> 
>     }
> 
>     MyLog.d(TAG, "识别出: ",boxList.size());
> 
>     return list;
> }
> 
> /**
>  * 在画布上绘制检测结果
>  * @param canvas 要绘制的画布
>  * @param boxes 检测结果列表
>  * @param paint 绘制时使用的画笔
>  */
> public void drawResults(Canvas canvas, List<YoloInfer.Box> boxes, Paint paint) {
>     YoloInfer.draw(canvas, boxes, paint);
> }
> ```
> 
> } 不行呀 识别出 0个 也不知道哪里出错了 也没有任何提示 这些写对还是不对？

已经对项目代码作了[更新](https://github.com/wkt/YoloMobile/releases/tag/v1.0.3r5), 并添加不用json示例:
https://github.com/wkt/YoloMobile/blob/main/app/src/main/java/com/weiketing/yolomobile/example/MainActivity.java

```
private void loadModel(String name)
    {

        infer = new YoloInfer(this);
        /*
        infer.setInputSize(384);
        infer.setParamName("last.param");
        infer.setBinName("last.bin");
        infer.loadModel();
        infer.setBoxThreshold(0.45f);
        infer.setIouThreshold(0.35f);
        infer.setNumKeypoint(5);
        infer.addOutput("397",8,new Float[]{10f,13f, 16f,30f, 33f,23f});
        infer.addOutput("458",16,new Float[]{30f,61f, 62f,45f, 59f,119f});
        infer.addOutput("519",32,new Float[]{116f,90f, 156f,198f, 373f,326f});

         */
        //infer.loadFromConfigAssets("cfg.json");
        modeName.setText("Model cfg: "+name);
        if(name.toLowerCase().endsWith("no-json")){
            infer.setInputSize(384);
            infer.setParamName("yolov5n_opt.param");
            infer.setBinName("yolov5n_opt.bin");
            infer.loadModel();
            infer.setBoxThreshold(0.45f);
            infer.setIouThreshold(0.35f);
            infer.setNumKeypoint(0);
            infer.addOutput("345",8,new Float[]{10f,13f, 16f,30f, 33f,23f});
            infer.addOutput("365",16,new Float[]{30f,61f, 62f,45f, 59f,119f});
            infer.addOutput("385",32,new Float[]{116f,90f, 156f,198f, 373f,326f});
        }else {
            if (!name.toLowerCase().endsWith(".json")) {
                name += ".json";
            }
            infer.loadFromConfigAssets(name);
        }
    }
```
