### ISSUE TITLE
.pt to ncnn ?

### ISSUE THREAD

**Issue by atengya** [wkt/YoloMobile#2]

**Comment by atengya** [comment]
大佬，我用你的代码跑yolov8的模型，但是无法识别。我是按照网上的转换教程来的，不知道出了什么问题。能不能讲一下如何转换模型和设置.json

**Comment by atengya** [comment]
OK，成功了，使用YOLOv8，使用yolov8自带的 
`model.export(format='ncnn')`
直接转换成ncnn。
前面我使用的是转换成onnx，再转换成ncnn，不知道为什么会失败

**Comment by wkt** [comment]
> OK，成功了，使用YOLOv8，使用yolov8自带的 `model.export(format='ncnn')` 直接转换成ncnn。 前面我使用的是转换成onnx，再转换成ncnn，不知道为什么会失败

pt->onnx->ncnn和model.export(format='ncnn')模型输出数据格式不一样
目前只支持model.export(format='ncnn')
