### ISSUE TITLE
 JNI DETECTED ERROR IN APPLICATION: fid == null in call to GetLongField

### ISSUE THREAD

**Issue by yeleibo** [wkt/YoloMobile#3]
在debug版本上没有问题，但是在release版本上会出问题，需要在proguard-rules.pro里面字段不混淆-keep class com.weiketing.yolomobile
可能的原因是：
分析代码发现YoloInfer_init方法里使用了固定变量名称_obj,在正式打包编译时会将名称_obj替换为别的变量名。造成YoloInfer_loadModel取不到。
![image](https://github.com/wkt/YoloMobile/assets/22091417/d6fa149a-0e89-450b-9c6b-b3e2fd079199)

**Comment by wkt** [comment]
多谢提醒，已在说明中添加了关于混淆的内容
