### ISSUE TITLE
请问可以做到实时检测吗？

### ISSUE THREAD

**Issue by Hermione-katy** [wkt/YoloMobile#5]
你好，我想问一下，如果想加上摄像头进行实现姿态检测，应该如何修改呢？

**Comment by wkt** [comment]
只要用小模型+小分辨率，Android上跑yolo达到实时也是可以的
现在已经在demo代码中，添加一个yolov8-pose-384模型，
在Mi 10 Lite Zoom手机上，这个模型处理图片的速度（选择模型配置，点击“TEST FPS”）可以到达18+FPS
如果需要使用摄像头，则须先把图像转为Bitmap

**Comment by Hermione-katy** [comment]
好的，非常感谢您的回复！！！
