### ISSUE TITLE
找不到 "libncnn.so"

### ISSUE THREAD

**Issue by kirer** [wkt/YoloMobile#7]
编译，启动后报错：
java.lang.UnsatisfiedLinkError: dlopen failed: library "libncnn.so" not found

**Comment by wkt** [comment]
运行环境贴一下，android版本，cpu类型等

**Comment by yytangsheng** [comment]
使用您的ncnn版本正常，升级到最新版本ncnn-20240410-android-vulkan-shared.zip后，打包正常，启动也是报"libncnn.so" not found
安卓9 vivox21a 
CPU核数：8
CPU位数：64-bit

**Comment by wkt** [comment]
> 使用您的ncnn版本正常，升级到最新版本ncnn-20240410-android-vulkan-shared.zip后，打包正常，启动也是报"libncnn.so" not found 安卓9 vivox21a CPU核数：8 CPU位数：64-bit

据说ncnn对vulkan支持不够优化，所以可以试试其它版

**Comment by yytangsheng** [comment]
您现在项目的ncnn是基于哪个版本的呢

**Comment by wkt** [comment]
> 您现在项目的ncnn是基于哪个版本的呢

https://github.com/wkt/YoloMobile/blob/d4f28a524e87c9ede1ba04cd901de29136c37414/YoloMobile/src/main/cpp/ncnn/x86_64/include/ncnn/platform.h#L64
`#define NCNN_VERSION_STRING "1.0.20230816"`

**Comment by kungoodbye** [comment]
> > 您现在项目的ncnn是基于哪个版本的呢
> 
> https://github.com/wkt/YoloMobile/blob/d4f28a524e87c9ede1ba04cd901de29136c37414/YoloMobile/src/main/cpp/ncnn/x86_64/include/ncnn/platform.h#L64
> 
> 
> `#define NCNN_VERSION_STRING "1.0.20230816"`

解决了吗，我也碰到了？没有编译进apk里

**Comment by wkt** [comment]
> 20240410

对方，没有再回应，我也不知道TA是否解决了？
你也是因为想换ncnn的版本，导致的问题么？
项目内置的nncnn是https://github.com/Tencent/ncnn/releases/download/20230816/ncnn-20230816-android-shared.zip

**Comment by wkt** [comment]
> > > 您现在项目的ncnn是基于哪个版本的呢
> > 
> > 
> > https://github.com/wkt/YoloMobile/blob/d4f28a524e87c9ede1ba04cd901de29136c37414/YoloMobile/src/main/cpp/ncnn/x86_64/include/ncnn/platform.h#L64
> > 
> > `#define NCNN_VERSION_STRING "1.0.20230816"`
> 
> 解决了吗，我也碰到了？没有编译进apk里

对方，没有再回应，我也不知道TA是否解决了？
你也是因为想换ncnn的版本，导致的问题么？
项目内置的ncnn是https://github.com/Tencent/ncnn/releases/download/20230816/ncnn-20230816-android-shared.zip

**Comment by yytangsheng** [comment]
> > > 您现在项目的ncnn是基于哪个版本的呢
> > 
> > 
> > https://github.com/wkt/YoloMobile/blob/d4f28a524e87c9ede1ba04cd901de29136c37414/YoloMobile/src/main/cpp/ncnn/x86_64/include/ncnn/platform.h#L64
> > 
> > `#define NCNN_VERSION_STRING "1.0.20230816"`
> 
> 解决了吗，我也碰到了？没有编译进apk里



> > > 您现在项目的ncnn是基于哪个版本的呢
> > 
> > 
> > https://github.com/wkt/YoloMobile/blob/d4f28a524e87c9ede1ba04cd901de29136c37414/YoloMobile/src/main/cpp/ncnn/x86_64/include/ncnn/platform.h#L64
> > 
> > `#define NCNN_VERSION_STRING "1.0.20230816"`
> 
> 解决了吗，我也听了？没有编译进apk里

我换成ncnn-20240410-android-shared 正常了，我是因为开始没有使用android-shared版本导致的
